### PR TITLE
Better image details

### PR DESCRIPTION
**Pull request by kcchik**
Screen Shot 2023-03-05 at 11 04 19 PM
can click on location to go to timeline
Screen Shot 2023-03-05 at 11 04 54 PM

### CODE REVIEW

**Review by Raymond-Xia — COMMENTED** [review]
Description text gets cut weird but looks swag asf 

image

**Comment by kcchik** [comment]
Screen Shot 2023-03-05 at 11 37 13 PM
@Raymond-Xia

**Comment by danielkim10** [comment]
if you want you can set the backgroundTint property of the image buttons to android:color/transparent to remove the boxes :sunglasses:

**Comment by Raymond-Xia** [comment]
> if you want you can set the backgroundTint property of the image buttons to android:color/transparent to remove the boxes 😎

i think i like the nice juicy square buttons to click in this case lol

**Review by Raymond-Xia — APPROVED** [review]

**Review by danielkim10 — APPROVED** [review]

**Pull request merged**
